name: Linters

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  id-token: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read


on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call:
    uses: opiproject/opi-smbios-bridge/.github/workflows/linters.yml@main
    secrets: inherit
